=== EV081/taller-serverless/data-setup/schemas-validation/empleados.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Empleados",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "local_id",
    "sort_key": "correo"
  },
  "properties": {
    "local_id": {
      "type": "string"
    },
    "correo": {
      "type": "string",
      "format": "email"
    },
    "contrasena": {
      "type": "string",
      "minLength": 6
    },
    "nombre": {
      "type": "string"
    },
    "apellido": {
      "type": "string"
    },
    "role": {
      "type": "string",
      "enum": [
        "Repartidor",
        "Cocinero"
      ]
    }
  },
  "required": [
    "local_id",
    "correo",
    "contrasena",
    "nombre",
    "apellido",
    "role"
  ],
  "additionalProperties": false
}

=== EV081/taller-serverless/data-setup/example-data/empleados.json
[
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "cocina@burger.com",
    "contrasena": "123456",
    "nombre": "Chef",
    "apellido": "Ramsay",
    "role": "Cocinero"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "delivery@burger.com",
    "contrasena": "123456",
    "nombre": "Flash",
    "apellido": "Gordon",
    "role": "Repartidor"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "andres.gonzalez@gmail.com",
    "contrasena": "emp_405422e8",
    "nombre": "Andrés",
    "apellido": "González",
    "role": "Repartidor"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "isabel.silva@outlook.com",
    "contrasena": "emp_2f5efe93",
    "nombre": "Isabel",
    "apellido": "Silva",
    "role": "Cocinero"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "camila.ortiz@outlook.com",
    "contrasena": "emp_4df77346",
    "nombre": "Camila",
    "apellido": "Ortiz",
    "role": "Repartidor"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "pedro.gonzalez@hotmail.com",
    "contrasena": "emp_684a088f",
    "nombre": "Pedro",
    "apellido": "González",
    "role": "Repartidor"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "ana.castro@gmail.com",
    "contrasena": "emp_adcf5d71",
    "nombre": "Ana",
    "apellido": "Castro",
    "role": "Cocinero"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "carlos.castro@outlook.com",
    "contrasena": "emp_756f7fa0",
    "nombre": "Carlos",
    "apellido": "Castro",
    "role": "Repartidor"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "juan.ortiz@hotmail.com",
    "contrasena": "emp_db0501d8",
    "nombre": "Juan",
    "apellido": "Ortiz",
    "role": "Repartidor"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "luis.flores@gmail.com",
    "contrasena": "emp_56432d4f",
    "nombre": "Luis",
    "apellido": "Flores",
    "role": "Cocinero"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "luis.sanchez@hotmail.com",
    "contrasena": "emp_c9a50267",
    "nombre": "Luis",
    "apellido": "Sánchez",
    "role": "Repartidor"
  },
  {
    "local_id": "BURGER-LOCAL-001",
    "correo": "diego.flores@outlook.com",
    "contrasena": "emp_2b80712c",
    "nombre": "Diego",
    "apellido": "Flores",
    "role": "Cocinero"
  }
]
